
import { Article } from './types';

export const ARTICLES: Article[] = [
  {
    id: 'a1',
    slug: 'how-i-became-a-subtitler',
    title: 'From New York to Île de Ré',
    subtitle: 'How I ended up subtitling films in France',
    category: 'Origin Story',
    date: 'February 2026',
    readTime: '7 min read',
    excerpt: "I didn't choose subtitling. Subtitling chose me — at 2 AM in a Parisian editing suite, with a deadline in four hours and a French director who didn't believe English could carry his poetry.",
    coverGradient: 'from-[#E35342] via-[#c2442e] to-[#8B2500]',
    categoryColor: '#E35342',
    content: [
      "I didn't choose subtitling. Subtitling chose me — at 2 AM in a Parisian editing suite, with a deadline in four hours and a French director who didn't believe English could carry his poetry.",
      "But let me back up. Way up. To a twenty-two-year-old American girl stepping off a plane at Charles de Gaulle with two suitcases and the kind of confidence that only comes from not knowing what you don't know.",
      "## The Arrival",
      "I moved to France the way some people fall in love — impulsively, irrationally, and with no exit plan. I'd studied French in college, done a semester abroad in Aix-en-Provence, and decided that my life needed more croissants and fewer cubicles. My parents thought it was a phase. Twenty-something years later, I'm writing this from Île de Ré, watching the tide come in through my office window, so I suppose the phase stuck.",
      "The first years were humbling. My French was good enough to order wine but not good enough to argue with a landlord about a broken heater. I taught English in schools. I did odd translation jobs — instruction manuals, corporate brochures, a truly terrible tourism pamphlet for a château in the Loire Valley. I once spent three days translating a technical document about sewage treatment plants. It was exactly as glamorous as it sounds.",
      "## The Moment Everything Changed",
      "The shift happened by accident, as the best career moves often do. A friend of a friend was working at a small post-production studio in Paris. They had a short film heading to a festival and needed English subtitles. The budget was minimal. The timeline was impossible. 'You're American, right? And you speak French? How hard can it be?'",
      "Famous last words.",
      "I sat in that studio with the sound engineer, watching the film for the first time, and something clicked. Not the technical part — that was a disaster. I didn't know about reading speeds or character limits or shot changes. I didn't know that a subtitle couldn't just hang in the air while the camera cut to a new scene. I didn't know any of the rules.",
      "But I knew something else. I knew that when the actress whispered 'Je n'en peux plus' with tears streaming down her face, 'I can't take it anymore' wasn't the right translation. It was technically correct. But it didn't carry the exhaustion, the surrender, the weight of everything unsaid. What she meant was closer to 'I'm done.' Two words instead of five. Less literal, more true.",
      "> That night, I discovered that subtitling isn't translation. It's compression. It's taking the full, messy, beautiful complexity of human speech and distilling it into something that fits in 40 characters — without losing the soul.",
      "## Learning the Craft",
      "I taught myself EZTitles — the industry-standard software — the way you teach yourself anything in your twenties: badly at first, then obsessively. I took workshops. I read everything Jean-François Cornu had written about the philosophy of adaptation. I studied the ATAA norms until I could recite character limits in my sleep. Forty characters per line. Fifteen characters per second. Two lines maximum. Four frames minimum gap.",
      "But the real education came from watching films. Hundreds of them. Thousands. I'd watch the French audio and read the English subtitles simultaneously, my brain ping-ponging between languages, cataloging what worked and what didn't. I'd pause on a subtitle that made me wince and rewrite it in my head. I'd notice the moments where a great translator had found something elegant — a compression so clean you'd never know half the dialogue was missing.",
      "## Finding My Place",
      "Work came slowly, then all at once. A short film led to a documentary. A documentary led to a TV episode. A TV episode led to a call from a production company working on a feature that had been selected for Cannes.",
      "I remember that phone call. I was standing in my kitchen on Île de Ré, watching the salt marshes through the window, and someone was asking me if I could subtitle a film for the Semaine de la Critique. I said yes before my brain could catch up to what my mouth was doing.",
      "That film was 'Vincent Doit Mourir.' And working on it — the pressure, the precision, the collaboration with the director — confirmed what I'd felt in that studio years earlier. This wasn't just a job. This was the space where my two languages, my two cultures, my two selves came together into something useful. Something that mattered.",
      "## The Island Life",
      "People always ask why Île de Ré. Why not Paris, where the studios are? The answer is simple: I think better near the ocean. The rhythm of the tides matches the rhythm of subtitling — patience, then urgency, then patience again. And in an age of remote work and digital deliveries, geography matters less than it used to. My deadlines don't care where I am. My EZTitles software works the same with a view of salt marshes as it does with a view of the Périphérique.",
      "Besides, there's something poetic about living on an island and building bridges for a living. Even if those bridges are made of forty characters at a time.",
      "> Looking back, I realize that every detour — the sewage treatment manuals, the terrible tourism pamphlets, the years of not quite fitting in — was preparation. You can't translate between cultures unless you've lived between them. You can't compress meaning unless you've spent years expanding your understanding of it.",
      "I still don't know if I chose this career or if it chose me. But I know that every time I sit down with a new film, I feel that same click I felt in that Parisian studio at 2 AM — the moment when two languages meet and something new is born in the space between them."
    ]
  },
  {
    id: 'a2',
    slug: 'the-40-character-cage',
    title: 'How Subtitling Actually Works',
    subtitle: '40 characters, 1.5 seconds, and zero room for error',
    category: 'Craft',
    date: 'February 2026',
    readTime: '8 min read',
    excerpt: "Imagine writing a novel where every sentence must be exactly 40 characters long, appear for precisely 1.5 seconds, and make a stranger in Tokyo cry at the same moment as a stranger in Brooklyn.",
    coverGradient: 'from-[#1a1a1a] via-[#2d2d2d] to-[#E35342]',
    categoryColor: '#F2E3CF',
    content: [
      "Imagine writing a novel where every sentence must be exactly 40 characters long, appear for precisely 1.5 seconds, and make a stranger in Tokyo cry at the same moment as a stranger in Brooklyn. That, roughly, is what subtitling feels like.",
      "People think subtitling is typing what someone says in another language. It's not. It's closer to haiku than to translation — an art of compression where every character counts, every millisecond matters, and the best work is the work nobody notices.",
      "## The Rules of the Cage",
      "Let me give you the constraints I work within every day. In cinema, a subtitle can have a maximum of 40 to 42 characters per line. Two lines maximum. The viewer needs to read at roughly 15 characters per second — any faster and the brain rebels, any slower and you're wasting precious screen time. There must be a minimum gap of four frames between consecutive subtitles, and a subtitle should never straddle a shot change.",
      "If a camera cuts from a close-up to a wide shot while your subtitle is on screen, the viewer's eye reflexively re-reads the text. That fraction of a second of cognitive disruption is enough to break immersion. So you snap your subtitle to end before the cut, or begin after it. Frame by frame. Twenty-four frames per second in cinema. You're making decisions at the level of forty-millisecond intervals.",
      "These aren't arbitrary rules. They're the physics of human reading. Decades of research and practice have established that these constraints are what allow a viewer to read a subtitle and watch a film simultaneously — without feeling like they're doing either one.",
      "## The Art of Cutting",
      "Here's the part that surprises people: you have to cut roughly 30% of everything that's said. A character speaks for six seconds, but you only have space for four seconds of text. Something has to go. The question is: what?",
      "Bad subtitlers cut meaning. Good subtitlers cut filler. Great subtitlers cut in a way that nobody notices.",
      "> In French, a character might say: 'Bon, écoute, je ne sais pas, franchement, c'est un peu compliqué tout ça, tu vois.' A word-for-word translation would be: 'Well, listen, I don't know, honestly, it's all a bit complicated, you know.' That's 73 characters. I have 42. The subtitle reads: 'It's complicated.' And if I've done my job, those two words carry all the hesitation, the weariness, the not-wanting-to-deal-with-it that was in the original.",
      "The secret is knowing what to protect. In every line of dialogue, there's a nucleus — the irreducible core of meaning — and there's everything else. The fillers ('bon,' 'alors,' 'du coup'), the repetitions, the verbal tics — these can usually go. But here's the trap: in auteur cinema, sometimes those fillers ARE the meaning. A character's 'du coup... du coup...' might be the sound of someone falling apart. Cut it and you've cut the emotion.",
      "## Segmentation: Where You Break the Line Matters",
      "Most viewers never think about where a subtitle line breaks. But it's one of the most important decisions I make. A badly segmented subtitle forces the eye to jump awkwardly between lines, creating micro-confusion.",
      "Consider the difference between these two options for the same subtitle. The first breaks the line after 'I told': 'I told / him that it was over.' The second breaks it after a natural pause: 'I told him / that it was over.' The second version follows the natural syntax of English. Your eye doesn't stumble. You read it the way you'd hear it. The first version leaves 'I told' dangling, forcing a cognitive bridge to the next line.",
      "Multiply this by seven hundred subtitles in a feature film, and you start to understand why good segmentation is the invisible backbone of good subtitling.",
      "## The Shot Change Dance",
      "My software — EZTitles — shows me a waveform of the audio and a frame-by-frame view of the video. Every cut in the film is marked. My job is to choreograph the subtitles around these cuts like a dancer navigating obstacles.",
      "Sometimes it's elegant. The character finishes a sentence, I end the subtitle, the camera cuts, and a new subtitle appears with the new shot. Beautiful. Clean.",
      "Sometimes it's a nightmare. A character speaks across three rapid cuts — close-up, reaction shot, wide shot — in four seconds. I have to decide: do I keep one subtitle across all three cuts (accepting the re-read disruption), or do I break it into three subtitles (each too short to read comfortably)? There's no formula. It's judgment. Experience. Instinct.",
      "## Translation is the Easy Part",
      "Here's what I tell people who think subtitling is 'just translation': the translation is maybe 40% of the job. The other 60% is timing, segmentation, compression, and the constant negotiation between what the character says, what the viewer needs, and what the screen can hold.",
      "> When it works — when the subtitles are invisible, when the viewer laughs at the joke at exactly the right moment, when someone in a dark theater doesn't even register that they're reading — that's the magic. The cage becomes a dance floor.",
      "I've been doing this for years and I still feel a small thrill when a subtitle lands perfectly. Forty characters. One and a half seconds. The exact right words in the exact right place at the exact right time. There are worse ways to spend a life."
    ]
  },
  {
    id: 'a3',
    slug: 'subtitles-cinema-secret-weapon',
    title: 'Subtitles Changed Cinema',
    subtitle: 'How subtitled films went from niche to mainstream',
    category: 'Industry',
    date: 'February 2026',
    readTime: '6 min read',
    excerpt: "Bong Joon-ho said it best: 'Once you overcome the one-inch-tall barrier of subtitles, you will be introduced to so many more amazing films.' I've spent my career building that one-inch bridge.",
    coverGradient: 'from-[#E35342] via-[#F2E3CF] to-[#E35342]',
    categoryColor: '#E35342',
    content: [
      "Bong Joon-ho said it best at the Golden Globes: 'Once you overcome the one-inch-tall barrier of subtitles, you will be introduced to so many more amazing films.' The audience laughed. But he wasn't joking. He was describing the single biggest unlock in modern cinema.",
      "I've spent my career building that one-inch bridge. And I've watched, with quiet satisfaction, as the world finally started crossing it.",
      "## The Streaming Revolution Nobody Predicted",
      "Something extraordinary happened in the last decade. Subtitled content went from niche to mainstream. Not gradually — explosively. 'Parasite' won the Oscar for Best Picture. 'Squid Game' became the most-watched series in Netflix history. 'Lupin' made a French gentleman thief a global star. 'Money Heist' turned a Spanish heist drama into a cultural phenomenon.",
      "None of this was supposed to happen. Hollywood had spent decades operating under the assumption that American audiences wouldn't read subtitles. The conventional wisdom was ironclad: dub everything, or don't bother. Foreign-language content was for art-house theaters and film festivals, not for mainstream Friday-night viewing.",
      "Streaming platforms shattered that assumption — not through idealism, but through data. Netflix discovered that subscribers who watched subtitled content stayed longer. The algorithm didn't care about the 'one-inch barrier.' It cared about engagement. And foreign-language content was engaging.",
      "## The Translator as Invisible Co-Author",
      "Here's what most viewers don't realize: when you watch a subtitled film, you're not just watching the director's vision. You're watching the translator's interpretation of the director's vision. Every line of dialogue has been filtered through a human mind that made hundreds of decisions about word choice, rhythm, register, and cultural context.",
      "When Omar Sy's character in 'Lupin' code-switches between polished French and banlieue slang, someone had to decide how to render that shift in English. When the characters in 'Call My Agent!' make inside jokes about the French film industry, someone had to judge which references would land and which needed subtle adaptation.",
      "> That 'someone' is the subtitler. We are the invisible co-authors of every international hit. We don't write the story — but we write the version of the story that the world actually reads.",
      "## When Bad Subtitles Kill",
      "The flip side is equally true: bad subtitles can destroy a masterpiece. I've watched brilliant films undone by lazy, machine-generated, or poorly timed subtitles. The comedy that wasn't funny because the punchline appeared two seconds late. The thriller that wasn't tense because the subtitle was so long the viewer had to choose between reading and watching. The drama that felt flat because every character sounded the same in English, even though they had distinct voices in French.",
      "The 'Lupin' dubtitle controversy was a perfect case study. Many English subtitles were derived from the dubbing script — text written for lip-sync, not for direct translation. The result was a cognitive dissonance for anyone who understood even basic French. The subtitles said one thing; the audio said another. The character's sociolinguistic identity — the very thing that made Assane Diop interesting — was flattened.",
      "## Subtitles as Cultural Bridge, Not Barrier",
      "The best argument for subtitles over dubbing is simple: subtitles preserve the original performance. You hear the actor's real voice, their real emotion, their real rhythm. The subtitle adds information; it doesn't replace anything.",
      "Dubbing, by contrast, replaces the voice entirely. No matter how skilled the voice actors, something is always lost — the breath between words, the crack of emotion, the specific musicality of the original language. When you watch 'Parasite' dubbed, you're not really watching 'Parasite.' You're watching an approximation.",
      "Subtitles trust the audience. They say: you're smart enough to read and watch at the same time. You're curious enough to hear a language you don't speak. You're sophisticated enough to appreciate that the world is bigger than one language.",
      "## The Future Is Multilingual",
      "The global language services market is valued at over $60 billion and growing. Streaming platforms are investing more than ever in original content from non-English-speaking countries. The European Union's Audiovisual Media Services Directive requires at least 30% European works in streaming catalogs. Accessibility regulations are expanding the demand for subtitled content.",
      "The future of cinema is not monolingual. It's not even bilingual. It's multilingual, multicultural, and increasingly dependent on the humans who build bridges between languages.",
      "> Every subtitle is an act of faith — faith that a story born in one language can live in another. That the emotion a French director poured into a scene can reach an audience in Seoul or São Paulo or San Francisco. That words, carefully chosen and precisely timed, can make the foreign familiar without making it less foreign.",
      "The one-inch barrier isn't a barrier at all. It's a doorway. And the best films in the world are waiting on the other side."
    ]
  },
  {
    id: 'a4',
    slug: 'what-ai-gets-wrong',
    title: 'What AI Gets Wrong About Translation',
    subtitle: 'Where machines still fall short',
    category: 'AI & Craft',
    date: 'February 2026',
    readTime: '8 min read',
    excerpt: "The machine translated it perfectly. Every word was correct. And yet, the joke was dead, the tension was gone, and the character sounded like a customer service bot.",
    coverGradient: 'from-[#212121] via-[#E35342] to-[#212121]',
    categoryColor: '#E35342',
    content: [
      "The machine translated it perfectly. Every word was correct. And yet, the joke was dead, the tension was gone, and the character sounded like a customer service bot. Welcome to the uncanny valley of AI subtitling.",
      "I want to be clear from the start: I'm not anti-technology. I use technology every day. My subtitling software is a marvel of engineering. Automated speech recognition saves me hours of transcription work. Quality-control tools catch technical errors that my eyes might miss at 3 AM. Technology is my partner.",
      "But technology is not my replacement. Not yet. And possibly not ever — at least not for the kind of work that matters most.",
      "## What AI Does Well",
      "Let me give AI its due. In 2026, machine translation is genuinely impressive for certain tasks. It handles straightforward, informational content with remarkable accuracy. Technical documentation. Corporate communications. Simple news articles. For bulk content where 'good enough' is genuinely good enough, AI is fast, cheap, and serviceable.",
      "In the subtitling pipeline specifically, AI excels at the mechanical layers: automatic speech recognition to generate transcripts, rough timing suggestions based on audio analysis, format conversion between subtitle standards, and automated checks for reading speed and character count violations. These are valuable. They free up human time for the work that actually requires a human brain.",
      "## Where It Falls Apart",
      "The problems start when AI encounters the things that make cinema interesting: ambiguity, subtext, cultural specificity, humor, and voice.",
      "Let me give you a concrete example. In French, 'C'est pas faux' literally translates to 'That's not wrong.' But depending on context, tone, and character, it could mean 'You have a point,' 'I reluctantly agree,' 'I'm being sarcastic and I think you're an idiot,' or 'I genuinely hadn't thought of it that way.' AI picks one. A human subtitler reads the scene — the actor's face, the other character's reaction, the dramatic context — and picks the right one.",
      "> The fundamental limitation isn't linguistic. It's perceptual. AI reads text. Subtitlers read scenes. We process dialogue, image, sound design, editing rhythm, and dramatic context simultaneously. We know that when a character says 'Fine' while slamming a door, the subtitle might need an exclamation point that isn't in the audio. We know that silence after a question can mean more than the answer.",
      "## The Register Problem",
      "One of the most insidious AI failures is what I call 'register flattening.' Every character in a well-written film has a distinct way of speaking — their vocabulary, their sentence structure, their verbal tics. A teenager doesn't speak like a professor. A gangster doesn't speak like a diplomat.",
      "AI tends to normalize everything into a middle register. It produces grammatically correct, tonally neutral text that could have been written by anyone. Or no one. The professor and the teenager start to sound the same. The gangster sounds polite. The diplomat sounds generic.",
      "In French cinema, this is catastrophic. French dialogue is extraordinarily sensitive to register. The shift from 'vous' to 'tu,' the deployment of verlan (backslang from the banlieues), the precise level of literary sophistication in a character's speech — these aren't decorations. They're characterization. Flatten the register and you flatten the character.",
      "## The Humor Graveyard",
      "Humor is where AI goes to die. I say this without pleasure — I wish AI could handle humor, because comedy subtitling is exhausting. But humor depends on timing, cultural context, surprise, and shared references. It's the most context-dependent form of language.",
      "A French pun that hinges on the double meaning of 'avocat' (lawyer/avocado) can't be translated literally. It needs to be recreated — a new joke that serves the same dramatic function in the same number of characters in the same amount of time. AI doesn't recreate. It translates. And the joke dies on the screen.",
      "## Machine Translation Post-Editing: Harder Than It Sounds",
      "The industry's current compromise is MTPE — Machine Translation Post-Editing. AI generates a first draft; a human cleans it up. In theory, this should be the best of both worlds. In practice, it's often the worst.",
      "Professional translators and their associations have raised a troubling concern: editing a flawed machine translation can be more cognitively demanding than translating from scratch. The brain has to simultaneously read the machine's output, compare it to the source, detect errors that are often subtle (plausible but wrong), resist the anchoring effect of the machine's word choices, and produce a corrected version. It's mentally exhausting in a way that original translation isn't.",
      "And there's an economic trap. Because MTPE is perceived as 'just editing,' rates are lower than for original translation. But the cognitive work is often equal or greater. The result is translators working harder for less money, producing work that's frequently worse than what they'd create from scratch. The European audiovisual translation community has been vocal about this — and they're right.",
      "## The Hybrid Future",
      "I don't think AI will replace human subtitlers for premium content. I think it will replace humans for bulk content — and that's fine. Reality TV, catalogue titles, corporate videos: AI will handle most of that, and the world won't suffer.",
      "But for cinema, for auteur television, for literary adaptations — for everything that depends on voice, nuance, cultural intelligence, and creative judgment — the human translator isn't a luxury. They're a necessity.",
      "> The realistic future is a partnership. AI handles the transcription, the timing suggestions, the format compliance, the repetitive checks. Humans handle the art. The choosing. The knowing-when-to-break-the-rules. The understanding that 'Fine' doesn't always mean 'Fine.'",
      "The best subtitles are the ones you don't notice. And the reason you don't notice them is that a human being — someone who lives between two languages and two cultures — made a thousand invisible decisions to keep you inside the story. No machine does that yet. I'll let you know when one does."
    ]
  },
  {
    id: 'a5',
    slug: 'cannes-at-3am',
    title: 'Cannes at 3 AM',
    subtitle: 'Subtitling a film for its festival premiere',
    category: 'Behind the Scenes',
    date: 'February 2026',
    readTime: '7 min read',
    excerpt: "The screening was in nine hours. The director had just recut the final scene. And I was staring at a subtitle file that no longer matched the film.",
    coverGradient: 'from-[#1a1a1a] via-[#E35342] to-[#F2E3CF]',
    categoryColor: '#F2E3CF',
    content: [
      "The screening was in nine hours. The director had just recut the final scene. And I was staring at a subtitle file that no longer matched the film.",
      "This is the reality of festival subtitling. Not the red carpet. Not the champagne on the Croisette. The reality is a darkened editing suite at 3 AM, your third espresso going cold, and the absolute certainty that if you make an error, several hundred of the world's most discerning film critics will see it tomorrow morning.",
      "## The Call",
      "It always starts with a phone call. A production company has a film in selection. It needs English subtitles. The deadline is — and this is the technical term — impossible. Films selected for Cannes are often still being edited weeks before the festival. Directors are perfectionists. They don't stop tweaking until the DCP is literally being encoded.",
      "The DCP — Digital Cinema Package — is the modern equivalent of a film print. It's what the projector reads. And the subtitles aren't burned into the image; they're a separate XML track, encoded frame by frame, that the projector overlays in real-time. This means your subtitle file must be frame-accurate. A drift of even a few frames over ninety minutes and your text starts sliding away from the dialogue. By the end of the film, characters are speaking and your subtitles are arriving like late guests at a dinner party.",
      "## The Rules of the Game",
      "Cannes doesn't forgive. The Marché du Film — the market screenings — has a hard delivery window. Your DCP must be on their platform days before the screening. Once it's delivered, it cannot be replaced. Let me repeat that: it cannot be replaced. There are no second takes. No patches. No 'we'll fix it in post.' The subtitle file you deliver is the subtitle file the world sees.",
      "Venice is equally unforgiving. Their guidelines explicitly warn: 'DCPs already delivered cannot be replaced.' Frame-accurate sync. Safe-title positioning. Correct encoding. Every technical requirement must be met on the first attempt, because there won't be a second.",
      "> This is why festival subtitling is not the same job as regular subtitling. Regular subtitling allows for review cycles, corrections, version updates. Festival subtitling is a no-regrets deliverable. You get one shot. The weight of that responsibility is physical — I feel it in my shoulders, in the tension in my jaw, in the way my eyes start burning at 2 AM.",
      "## The Night Before",
      "Let me walk you through a typical Cannes night. It's 8 PM. The screening is at 10 AM the next morning. I've been working on the subtitles for two weeks — a comfortable timeline by industry standards. The file is polished. The timing is clean. I've done a simulation pass — watching the film with subtitles in real-time to check rhythm and readability. Everything is ready.",
      "Then the phone rings. The director has recut the ending. Not massively — twelve seconds of additional footage, a different take of the final dialogue, and a slight rearrangement of the closing shots. Twelve seconds. It sounds trivial. It's not.",
      "Those twelve seconds cascade through the subtitle file. Every timecode after the cut point shifts. Shot changes move. Gaps between subtitles change. Reading speeds that were comfortable now might be too fast or too slow. And the new dialogue — even if it's only two or three lines — needs to be translated, timed, segmented, and checked against character limits.",
      "## The Process",
      "So I sit down. I open EZTitles. I load the new video file. I identify the cut point. I retime every subtitle from that point forward, adjusting for the twelve-second shift. I translate the new dialogue — three lines, but each one requiring thought because this is the ending, the emotional climax, the last thing the audience will read.",
      "I check shot changes. The rearranged closing shots have moved two cuts, which means two of my subtitles now straddle shot boundaries. I adjust their timing, splitting one subtitle into two and condensing the text to fit the shorter duration.",
      "I run a quality check. Reading speeds: all within range. Character counts: fine. Minimum gaps: one violation — I adjust. Then I do another simulation pass. At this hour, with this level of fatigue, the simulation is the most important step. The numbers can say everything is correct, but the human eye watching the film with subtitles in real-time is the final test.",
      "## The Simulation",
      "The simulation is an AVT tradition, particularly in France. You sit in a screening room — or in my case, at this hour, in front of my monitor with good speakers — and you watch the film as a viewer would. You read the subtitles. You check: does this feel right? Does the rhythm match the speech? Is there a moment where your eye struggles? A line that feels too long? A subtitle that disappears before you've finished reading?",
      "It's 4 AM. The film plays. I read my own words on screen and I'm looking for the tiniest friction — the moment where reading stops being effortless and becomes work. Because if I feel it, the critic at the 10 AM screening will feel it too.",
      "## The Delivery",
      "At 5:30 AM, I export the final subtitle file. XML format, encoded to DCP specifications. I send it to the lab, where it will be wrapped into the Digital Cinema Package. I write a brief email confirming the delivery, noting the changes made and the timecodes affected.",
      "Then I close my laptop. I step outside. The sky over the Croisette — or in my case, over Île de Ré — is just beginning to lighten. And I think about the fact that in a few hours, in a dark theater in Cannes, hundreds of people will read my words and, if I've done my job, not think about them at all.",
      "> That's the paradox of this work. The highest praise is invisibility. The best outcome is that nobody notices. You pour everything into those forty-character lines — your skill, your judgment, your 3 AM espresso-fueled precision — and if it works, it disappears into the film like rain into the ocean.",
      "I love it. Every terrifying, exhausting, exhilarating minute of it."
    ]
  },
  {
    id: 'a6',
    slug: 'between-two-tongues',
    title: 'Living in Two Languages',
    subtitle: 'How being bilingual shapes the way I translate',
    category: 'Personal',
    date: 'February 2026',
    readTime: '6 min read',
    excerpt: "I argue differently in French than I do in English. I'm funnier in French, more precise in English. And somewhere in between those two versions of myself, I found my career.",
    coverGradient: 'from-[#F2E3CF] via-[#E35342] to-[#212121]',
    categoryColor: '#F2E3CF',
    content: [
      "I argue differently in French than I do in English. I'm funnier in French, more precise in English. And somewhere in between those two versions of myself, I found my career.",
      "Living bilingually is not what people think it is. It's not a switch you flip — English on, English off, French on, French off. It's more like a radio dial, constantly tuning between frequencies, sometimes catching both at once, sometimes landing in the static between stations where neither language quite works.",
      "## The Two Selves",
      "There's a body of research suggesting that bilinguals have slightly different personalities in each language. I don't need research to tell me this. I live it every day.",
      "In English, I'm direct. I get to the point. I use short sentences and active verbs. My humor is dry, observational, a little New York. In French, I'm more elaborate. I take the scenic route through a sentence. I use the subjunctive (and enjoy it). My humor is more playful, more absurdist — there's a whole register of French comedy that has no English equivalent.",
      "Neither version is fake. Both are me. But they're different me's, shaped by the different architectures of the languages they inhabit.",
      "> English is a language of nouns and verbs. It wants to know what happened. French is a language of relationships between ideas. It wants to know how things are connected. When I translate, I'm not just converting words. I'm converting worldviews.",
      "## The Untranslatable",
      "Every bilingual person has a collection of words that refuse to cross the border. Mine includes:",
      "'Dépaysement' — the feeling of being in a foreign country. English has no single word for this sensation. 'Disorientation' is too negative. 'Culture shock' is too clinical. 'Dépaysement' is neutral, even positive — it's the vertigo of being somewhere new, stripped of your usual reference points.",
      "'Terroir' — the taste of a place in its food and wine. You can explain it, but you can't translate it. 'Terroir' carries centuries of French agricultural philosophy in seven letters.",
      "'Home' — going the other direction, French has 'maison' (house) and 'chez moi' (at my place), but neither captures the emotional weight of the English word 'home.' 'Home' is warm, safe, belonging. 'Maison' is a building. The gap between them is vast.",
      "These untranslatable words aren't failures of language. They're proof that different cultures have carved up reality in different ways. And translation — real translation, not word-swapping — is the art of carrying meaning across those different maps of reality.",
      "## The Space Between",
      "The most interesting place in my bilingual brain is not the French zone or the English zone. It's the space between them. That's where my work happens.",
      "When I subtitle a film, I'm not thinking in French and then translating into English. I'm not thinking in English and mapping it onto French. I'm in the in-between — a liminal space where I hold the meaning of the French dialogue and the constraints of the English subtitle simultaneously, looking for the point where they meet.",
      "Sometimes they meet easily. 'Bonjour' becomes 'Hello' and we move on. But mostly, they meet at an angle, and my job is to find the compromise that loses the least.",
      "A character says 'J'en ai marre' — literally 'I've had enough of it,' but in practice it's closer to 'I'm so done' or 'I'm sick of this' or 'I can't deal' depending on age, context, and emotion. The French phrase is elastic. The English subtitle must pick one point on that elastic and commit to it. The in-between is where I make that choice.",
      "## What Translation Really Is",
      "People often ask me: 'Do you think in French or in English?' The honest answer is: neither. Or both. When I'm deep in a translation, I'm not thinking in any specific language. I'm thinking in meaning — raw, pre-verbal meaning — and then reaching for the best words to express it in the target language.",
      "This is what translation really is. It's not a bridge between two languages. It's a dive beneath both of them, down to the level where meaning exists without words, and then a resurfacing in the other language. The best translators are the ones who can hold their breath the longest — who can stay in that wordless space of pure meaning and not grab the first word that floats by.",
      "> After twenty-plus years of living between French and English, I've come to think that the space between languages is the most honest place in the world. It's where pretension falls away, where clichés don't work, where you have to find what you actually mean because neither language will let you hide behind familiar phrases.",
      "## The Gift",
      "Living bilingually is disorienting, exhausting, and occasionally lonely. There are days when I can't find the word I need in either language — it exists in the gap, and neither French nor English will claim it. There are social situations where I forget which language I started a sentence in. There are moments of deep, existential weirdness when I realize that my sense of humor, my emotional reflexes, my very sense of self shifts depending on which language I'm speaking.",
      "But it's also a gift. Because that disorientation — that permanent, low-grade dépaysement — is exactly what makes me good at my job. I live in the space between languages. I've built my home there. And every time I sit down to subtitle a film, I'm drawing on twenty years of navigating the gap between two ways of seeing the world.",
      "The best translation doesn't come from knowing two languages perfectly. It comes from knowing the space between them intimately. That's where I live. That's where the work gets done."
    ]
  }
];
